### ISSUE TITLE
Can I use Objective-CUPS for iOS?

### ISSUE THREAD

**Issue by ZuzooVn** [eahrold/Objective-CUPS#5]

**Comment by eahrold** [comment]
Hey @ZuzooVn,
Long story short no. It requires libCups which isn't accessible on the iOS platform.

I toyed with this idea a bit at the inception of OC. Ultimately even if you were able to compile your app with libCups,  and successfully add printers, you would be limited to printing only from the singular app because of sandboxing, so I abandoned further exploration.

But if you do decide to go forward, PR's are always welcome.

Thanks.
